baseURL = 'http://www.parichaya.tech/'
languageCode = 'en-us'
theme = 'graysx'
title = 'Parichaya'

## Site Settings
[params]
logo = "assets/img/logo.webp"
favicon = "assets/img/oooo.webp"

# Info
address = "Salt Lake Sector V, Kolkata- 700091"
email = "souvikh@hornet.technology"
phone = "+91 8653149116"

# Socials

twitter = "https://twitter.com/hornetdefiant"
instagram = "#"
github = "https://github.com/akatiggerx04/graysx-hugo"

# Other

# Startbootstrap Contact Form Token https://startbootstrap.com/solution/contact-forms
sbtoken = "8395bdf3-5736-4ef7-9c87-6f6fd126787f"

## Menu Items
[menu]
  [[menu.main]]
  name = "About"
  URL = "#about"
  weight = 1

  [[menu.main]]
  name = "Vision"
  URL = "#projects"
  weight = 2

  [[menu.main]]
  name = "Contact"
  URL = "#signup"
  weight = 3


